name: Pre-Merge Check

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["*"]

jobs:
   check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Server
      - name: Install server deps
        working-directory: ./server
        run: npm install

      - name: Test server startup
        working-directory: ./server
        run: |
          # Start server in background
          npm start &
          SERVER_PID=$!

          # Wait for server to start
          sleep 5

          # Check if server is still running
          if kill -0 $SERVER_PID 2>/dev/null; then
            echo "Server started successfully"
            kill $SERVER_PID
            exit 0
          else
            echo "Server failed to start"
            exit 1
          fi

      # Client
      - name: Install client deps
        working-directory: ./client
        run: npm install

      - name: Build client
        working-directory: ./client
        run: npm run build
